"""Versioned rules for the v0.5 void beacon extension."""

from __future__ import annotations

VOID_BEACON_CONTENT_VERSION = "content-0.5"
VOID_BEACON_RULE_VERSION = "social-0.5.0"
VOID_BEACON_ANCHOR_COST = 10
VOID_BEACON_SAND_COST = 30
VOID_BEACON_BUILD_SECONDS = 24 * 60 * 60
VOID_BEACON_MAINTENANCE_ANCHOR_COST = 2
VOID_BEACON_ROUTE_DISCOUNT = 1


__all__ = [
    "VOID_BEACON_ANCHOR_COST",
    "VOID_BEACON_BUILD_SECONDS",
    "VOID_BEACON_CONTENT_VERSION",
    "VOID_BEACON_MAINTENANCE_ANCHOR_COST",
    "VOID_BEACON_ROUTE_DISCOUNT",
    "VOID_BEACON_RULE_VERSION",
    "VOID_BEACON_SAND_COST",
]
