"""Small shared utilities with no game-domain rules."""

from .database import connect_sqlite
from .json_cache import DuplicateJSONKeyError, clear_json_cache, read_json_cached
from .json import json_object
from .player import (
    PLAYER_RESOURCE_FIELDS,
    player_field,
    player_integer,
    player_numeric_values,
    player_object,
    player_inventory,
    player_resource_values,
    player_qualification,
    player_intro_flags,
    player_combat_values,
    player_reputation,
    player_values,
)
from .assets import (
    AssetState,
    AssetDeltaError,
    apply_player_assets,
    assets_grant,
    assets_spend,
    assets_with_delta,
    change_player_assets,
    currency_grant,
    currency_spend,
    currency_with_delta,
    grant_player_assets,
    inventory_amount,
    inventory_grant,
    inventory_json,
    inventory_missing,
    inventory_spend,
    inventory_value,
    inventory_with_delta,
    player_asset_state,
    spend_player_assets,
    write_player_values,
    write_player_assets,
)

__all__ = [
    "AssetDeltaError",
    "AssetState",
    "PLAYER_RESOURCE_FIELDS",
    "apply_player_assets",
    "assets_grant",
    "assets_spend",
    "assets_with_delta",
    "change_player_assets",
    "DuplicateJSONKeyError",
    "clear_json_cache",
    "connect_sqlite",
    "currency_grant",
    "currency_spend",
    "currency_with_delta",
    "grant_player_assets",
    "inventory_amount",
    "inventory_grant",
    "inventory_json",
    "inventory_missing",
    "inventory_spend",
    "inventory_value",
    "inventory_with_delta",
    "player_asset_state",
    "json_object",
    "player_field",
    "player_integer",
    "player_numeric_values",
    "player_object",
    "player_inventory",
    "player_qualification",
    "player_intro_flags",
    "player_combat_values",
    "player_reputation",
    "player_resource_values",
    "player_values",
    "read_json_cached",
    "spend_player_assets",
    "write_player_values",
    "write_player_assets",
]
