"""Player-made profession works required by the dao-union quest."""

from __future__ import annotations

from .recipe_models import RecipeDefinition


CONTENT_VERSION = "content-0.6"
RULE_VERSION = "production-0.6.0"
SUPPORT_SUBPROFESSIONS = ("alchemy", "artifice", "formation")

ENDGAME_WORK_RECIPES = {
    "recipe.masterwork.body": RecipeDefinition(
        key="recipe.masterwork.body",
        name="体修大师作品",
        profession=None,
        inputs={"item.material.cloud_iron": 20, "item.domain_core": 2},
        energy_cost=20,
        duration_seconds=2 * 60 * 60,
        daily_limit=1,
        tool_key=None,
        tool_cost_bp=0,
        currency_cost=0,
        outputs={"item.masterwork.body": 1},
        high_quality_bonus={},
        failure_refunds={"item.material.cloud_iron": 10, "item.domain_core": 1},
        min_realm_layer=10,
        required_realm="void_refining",
        required_path="body",
        content_version=CONTENT_VERSION,
        rule_version=RULE_VERSION,
    ),
    "recipe.masterwork.spell": RecipeDefinition(
        key="recipe.masterwork.spell",
        name="法修大师作品",
        profession=None,
        inputs={"item.void_crystal": 20, "item.soul_crystal": 6},
        energy_cost=20,
        duration_seconds=2 * 60 * 60,
        daily_limit=1,
        tool_key=None,
        tool_cost_bp=0,
        currency_cost=0,
        outputs={"item.masterwork.spell": 1},
        high_quality_bonus={},
        failure_refunds={"item.void_crystal": 10, "item.soul_crystal": 3},
        min_realm_layer=10,
        required_realm="void_refining",
        required_path="spell",
        content_version=CONTENT_VERSION,
        rule_version=RULE_VERSION,
    ),
    "recipe.masterwork.device": RecipeDefinition(
        key="recipe.masterwork.device",
        name="器修大师作品",
        profession=None,
        inputs={"item.material.cloud_iron": 15, "item.void_crystal": 10, "item.domain_core": 1},
        energy_cost=20,
        duration_seconds=2 * 60 * 60,
        daily_limit=1,
        tool_key=None,
        tool_cost_bp=0,
        currency_cost=0,
        outputs={"item.masterwork.device": 1},
        high_quality_bonus={},
        failure_refunds={"item.material.cloud_iron": 8, "item.void_crystal": 5, "item.domain_core": 1},
        min_realm_layer=10,
        required_realm="void_refining",
        required_path="device",
        content_version=CONTENT_VERSION,
        rule_version=RULE_VERSION,
    ),
    "recipe.masterwork.demonic": RecipeDefinition(
        key="recipe.masterwork.demonic",
        name="魔修大师作品",
        profession=None,
        inputs={"item.demon_core": 12, "item.soul_crystal": 6},
        energy_cost=20,
        duration_seconds=2 * 60 * 60,
        daily_limit=1,
        tool_key=None,
        tool_cost_bp=0,
        currency_cost=0,
        outputs={"item.masterwork.demonic": 1},
        high_quality_bonus={},
        failure_refunds={"item.demon_core": 6, "item.soul_crystal": 3},
        min_realm_layer=10,
        required_realm="void_refining",
        required_path="demonic",
        content_version=CONTENT_VERSION,
        rule_version=RULE_VERSION,
    ),
    "recipe.masterwork.beast": RecipeDefinition(
        key="recipe.masterwork.beast",
        name="妖修大师作品",
        profession=None,
        inputs={"item.beast_blood": 12, "item.void_crystal": 8},
        energy_cost=20,
        duration_seconds=2 * 60 * 60,
        daily_limit=1,
        tool_key=None,
        tool_cost_bp=0,
        currency_cost=0,
        outputs={"item.masterwork.beast": 1},
        high_quality_bonus={},
        failure_refunds={"item.beast_blood": 6, "item.void_crystal": 4},
        min_realm_layer=10,
        required_realm="void_refining",
        required_path="beast",
        content_version=CONTENT_VERSION,
        rule_version=RULE_VERSION,
    ),
    "recipe.masterwork.alchemy": RecipeDefinition(
        key="recipe.masterwork.alchemy",
        name="炼丹大师作品",
        profession=None,
        inputs={"item.herb.blood_grass": 20, "item.soul_crystal": 3, "item.domain_core": 1},
        energy_cost=15,
        duration_seconds=90 * 60,
        daily_limit=1,
        tool_key=None,
        tool_cost_bp=0,
        currency_cost=0,
        outputs={"item.masterwork.alchemy": 1},
        high_quality_bonus={},
        failure_refunds={"item.herb.blood_grass": 10, "item.soul_crystal": 1},
        min_realm_layer=10,
        required_realm="void_refining",
        required_path="support",
        required_subprofession=SUPPORT_SUBPROFESSIONS,
        content_version=CONTENT_VERSION,
        rule_version=RULE_VERSION,
    ),
    "recipe.masterwork.artifice": RecipeDefinition(
        key="recipe.masterwork.artifice",
        name="炼器大师作品",
        profession=None,
        inputs={"item.material.cloud_iron": 15, "item.void_crystal": 5},
        energy_cost=15,
        duration_seconds=90 * 60,
        daily_limit=1,
        tool_key=None,
        tool_cost_bp=0,
        currency_cost=0,
        outputs={"item.masterwork.artifice": 1},
        high_quality_bonus={},
        failure_refunds={"item.material.cloud_iron": 7, "item.void_crystal": 2},
        min_realm_layer=10,
        required_realm="void_refining",
        required_path="support",
        required_subprofession=SUPPORT_SUBPROFESSIONS,
        content_version=CONTENT_VERSION,
        rule_version=RULE_VERSION,
    ),
    "recipe.masterwork.formation": RecipeDefinition(
        key="recipe.masterwork.formation",
        name="布阵大师作品",
        profession=None,
        inputs={"item.domain_core": 2, "item.void_crystal": 5},
        energy_cost=15,
        duration_seconds=90 * 60,
        daily_limit=1,
        tool_key=None,
        tool_cost_bp=0,
        currency_cost=0,
        outputs={"item.masterwork.formation": 1},
        high_quality_bonus={},
        failure_refunds={"item.domain_core": 1, "item.void_crystal": 2},
        min_realm_layer=10,
        required_realm="void_refining",
        required_path="support",
        required_subprofession=SUPPORT_SUBPROFESSIONS,
        content_version=CONTENT_VERSION,
        rule_version=RULE_VERSION,
    ),
    "recipe.masterwork.support": RecipeDefinition(
        key="recipe.masterwork.support",
        name="辅修三艺合成作品",
        profession=None,
        inputs={
            "item.masterwork.alchemy": 1,
            "item.masterwork.artifice": 1,
            "item.masterwork.formation": 1,
        },
        energy_cost=5,
        duration_seconds=30 * 60,
        daily_limit=1,
        tool_key=None,
        tool_cost_bp=0,
        currency_cost=0,
        outputs={"item.masterwork.support": 1},
        high_quality_bonus={},
        failure_refunds={
            "item.masterwork.alchemy": 1,
            "item.masterwork.artifice": 1,
            "item.masterwork.formation": 1,
        },
        min_realm_layer=10,
        required_realm="void_refining",
        required_path="support",
        required_subprofession=SUPPORT_SUBPROFESSIONS,
        content_version=CONTENT_VERSION,
        rule_version=RULE_VERSION,
    ),
}

RECIPE_ALIASES = {
    "体修大师作品": "recipe.masterwork.body",
    "法修大师作品": "recipe.masterwork.spell",
    "器修大师作品": "recipe.masterwork.device",
    "魔修大师作品": "recipe.masterwork.demonic",
    "妖修大师作品": "recipe.masterwork.beast",
    "炼丹大师作品": "recipe.masterwork.alchemy",
    "炼器大师作品": "recipe.masterwork.artifice",
    "布阵大师作品": "recipe.masterwork.formation",
    "辅修三艺合成作品": "recipe.masterwork.support",
}

ITEM_LABELS = {
    "item.material.cloud_iron": "云铁",
    "item.void_crystal": "虚空晶",
    "item.soul_crystal": "神魂晶",
    "item.domain_core": "领域核心",
    "item.demon_core": "魔核",
    "item.beast_blood": "兽血",
    "item.masterwork.body": "体修大师作品",
    "item.masterwork.spell": "法修大师作品",
    "item.masterwork.device": "器修大师作品",
    "item.masterwork.demonic": "魔修大师作品",
    "item.masterwork.beast": "妖修大师作品",
    "item.masterwork.alchemy": "炼丹大师作品",
    "item.masterwork.artifice": "炼器大师作品",
    "item.masterwork.formation": "布阵大师作品",
    "item.masterwork.support": "辅修三艺合成作品",
}

__all__ = [
    "CONTENT_VERSION",
    "ENDGAME_WORK_RECIPES",
    "ITEM_LABELS",
    "RECIPE_ALIASES",
    "RULE_VERSION",
    "SUPPORT_SUBPROFESSIONS",
]
